### ISSUE TITLE
truncate with decimals

### ISSUE THREAD

**Issue by birosz** [bartbutenaers/node-red-contrib-calc#11]
when you got the time and mood please add a truncate option for decimals too, the round to decimals is rounding up/down, while a trunc option could cut from 5 decimals to 2 decimals without rounding. (ex. 3.19 round to 1 decimal is 3.2 but trunc to 1 decimal is 3.1)
thank you!

**Comment by bartbutenaers** [comment]
Hi @birosz,

To be honest, I don't think anybody will ever be in the mood to add a truncate option ;-)

Since your proposal makes sense, I have added two features:

1. The truncate option is now available in the dropdown (similar to rounding):

   ![image](https://github.com/bartbutenaers/node-red-contrib-calc/assets/14224149/838a79cf-22ce-402f-8ec8-d4b7bd49e3b5)

2. The truncate can now also be applied to the result (of another calculation).  Of course rounding and truncating are mutually exclusive, so the checkboxes need to be unchecked automatically:

   ![mutual_exclusive](https://github.com/bartbutenaers/node-red-contrib-calc/assets/14224149/786721f9-f34e-4f1e-8b4c-9377ca2bebb0)

It would be nice if you could test both options (and the documentation), before I publish this on NPM and the Node-RED palette menu.

When you have Git installed, you can install this update directly from this Github repository via this command (executed within your .node-red folder):
```
npm install bartbutenaers/node-red-contrib-calc
```

Bart

**Comment by birosz** [comment]
hello Bart!
thanks for the fast reply, your node is very useful (and popular as i see from the number of downloads :D) .
i am trying to help you by testing it but since my knowledge is limited i don't know if i'm doing something wrong or not
(the closest i ever got to JS and even github was through and because of node-red and everything is self taught in this domain as i am an industrial automation engineer, plc, dcs and stuff).

git is installed as i checked it with:
```git --version```
according to the node-red documentation i created a local folder and i also added r/w rights:
```mkdir local_node```
```chmod 777 local_nodes```
then i ran the npm install command you gave, but even with ```sudo``` or ```-g``` option i got this:
```npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/bartbutenaers/node-red-contrib-cal.git
npm ERR! Warning: Permanently added 'github.com,140.82.121.4' (ECDSA) to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.```

sorry if i am doing something wrong, this is already nasa level for me, but still i'd really like to test it.
cheers

**Comment by birosz** [comment]
ok, tried again and for some reason started working;

![image](https://github.com/bartbutenaers/node-red-contrib-calc/assets/79317789/e88c9ce8-be8f-4752-8241-9468af31df74)

the truncate option is missing from the operation drop down list now

**Comment by birosz** [comment]
the "truncate" showed up, now if i select "truncate", and select done (and deploy), the operation will jump to "integer part"

**Comment by birosz** [comment]
also if i may add and if it is easy to implement for you like this; this "new" truncate should start the counting from the decimal point, because sometimes the integer part varies (ex: truncating 3.21 and 13.21 with a constant of 1 from decimal point should give 3.2 and 13.2)

**Comment by bartbutenaers** [comment]
Hi,

Thanks for all your test efforts ;-)

> ok, tried again and for some reason started working;

I 'think' the first time you forgot the "c" in the node name (because I see cal instead of cal***c***):

![image](https://github.com/bartbutenaers/node-red-contrib-calc/assets/14224149/a9468865-935b-4aae-bed0-2e052aca9b4b)

>  if i select "truncate", and select done (and deploy), the operation will jump to "integer part"

Ok so all your test efforts were useful.  How stupid of me.  Seems that a couple of years ago I already added a truncate option, but I called it *"integer part"*:

![image](https://github.com/bartbutenaers/node-red-contrib-calc/assets/14224149/cfbbc0f2-3967-4fef-a9b7-e53805645e4a)

Since accidentally both options have the same code *"trunc", Node-RED will select automatically the first option when you reopen the config screen...

I have added *"(truncate)"* to the label of the existing option, to make this more clear:

![image](https://github.com/bartbutenaers/node-red-contrib-calc/assets/14224149/a94ce462-70ee-4bcb-a78a-ab9a5abbb722)

> this "new" truncate should start the counting from the decimal point,

I have changed the label of the new option to make this more clear:

![image](https://github.com/bartbutenaers/node-red-contrib-calc/assets/14224149/c7b2460c-b796-49a9-9454-6bc659c3b494)

Now you can specify the number of decimals in the input array `[some_number_to_truncate, decimal_places]` or as a constant in the node's config screen (if you can simple want to inject a numeric value).

**Comment by birosz** [comment]
hello,
yep there was a typo when i tried to install it for the first time, also on the chmod command, but anyway,
i can confirm now it works as imagined;
![image](https://github.com/bartbutenaers/node-red-contrib-calc/assets/79317789/a8769902-5f59-42bb-82c5-c9fb37934453)
although if i may ask;
are you using some kind of general ui templatised thing for every "Operation" in the dropdown and some are redundant in this case? I think these two "parameters" are the same thing or maybe i just misunderstood it?
![image](https://github.com/bartbutenaers/node-red-contrib-calc/assets/79317789/627ac25d-2979-41fb-b251-f68cc256e997)
other than this, i havent found any problems with it.
thanks for the attention,
great work, enjoy your coffee!

**Comment by bartbutenaers** [comment]
Well I implemented this new truncate feature similar to the round feature:

![image](https://github.com/bartbutenaers/node-red-contrib-calc/assets/14224149/4fc44465-94ac-4593-9384-08cd0c485080)

+ In the dropdown you can select all kind of options, inclusive the rounding.
+ But if you select another option in the dropdown (e.g. maximum), then you can round the result of ANY operation using the *"round result to"* feature.

So both features have the same result, but they are used in different circumstances.

**Comment by bartbutenaers** [comment]
BTW your coffees tasted great this morning ;-)
Really appreciated!

**Comment by bartbutenaers** [comment]
Version ***1.0.6*** is now available in the palette:

![image](https://github.com/bartbutenaers/node-red-contrib-calc/assets/14224149/4d5feb13-8c81-4c9f-8eee-19f66d727317)
