### ISSUE TITLE
Constant allows integers only

### ISSUE THREAD

**Issue by aaronsb** [bartbutenaers/node-red-contrib-calc#3]
The constant field is integer only. Please make it support floating point.

**Comment by bartbutenaers** [comment]
Hi Aaron,
For some reason I have not seen your issue here, until I saw another new issue today ...
My apologies!
This is now fixed in version ***1.0.2***, which will be published on NPM somewhere this week ...

![image](https://user-images.githubusercontent.com/14224149/86060393-e9c94880-ba64-11ea-8ea1-b879cf632e54.png)

Kind regards,
Bart Butenaers

**Comment by aaronsb** [comment]
Thanks! I really appreciate the update. :)

**Comment by bartbutenaers** [comment]
Aaron,
FYII have published this feature on NPM in version **1.0.2**
Bart
